# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PhishDetect
email: nex@nex.sx
description: > # this means to ignore newlines until "baseurl:"
  PhishDetect is a tool to help identify suspected phishing pages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://phishdetect.io" # the base hostname & protocol for your site
twitter_username: phishdetectio
github_username:  phishdetect

# Build settings
markdown: kramdown

exclude:
    - node_modules
    - Makefile
