baseURL = "https://phishdetect.io/"
languageCode = "en-us"
title = "PhishDetect"
description = "PhishDetect is a tool to help at-risk users identify potential phishing attacks"

[[menu.main]]
	name = "Docs"
	url = "/docs/"
[[menu.main]]
	name = "FAQ"
	url = "/faq/"

